print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $ "))
percent = float(input("How much tip would you like to give? 10, 12, or 15? "))
people = float(input("How many people to split the bill? "))
tip = round(((percent / 100 + 1) * (bill / people)), 2)
print(f"Each person should pay: ${tip}")
